// ATLProject1.idl : IDL source for ATLProject1
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLProject1.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	uuid(7a67b5fa-4f33-4bb0-92dc-3bfa6c3cc09d),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{92c79de0-8a79-490d-ab10-f20bac52883c}")
]
library ATLProject1Lib
{
	importlib("stdole2.tlb");
	[
		uuid(92c79de0-8a79-490d-ab10-f20bac52883c)
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
};

